apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agent-msw
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        spec:
          imagePullSecrets:
          - name: pipeline-docker-registry
          containers:
          - name: agent-msw
            image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
            env:
              - name: API_URL
                valueFrom:
                  secretKeyRef:
                    name: agent-msw
                    key: API_URL
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: agent-msw
                    key: API_KEY
              - name: VALID_TO_PORT_UNLOCODES
                valueFrom:
                  secretKeyRef:
                    name: agent-msw
                    key: VALID_TO_PORT_UNLOCODES
              - name: MSW_REQUEST_URL
                valueFrom:
                  secretKeyRef:
                    name: agent-msw
                    key: MSW_REQUEST_URL
              - name: MSW_BASIC_AUTH
                valueFrom:
                  secretKeyRef:
                    name: agent-msw
                    key: MSW_BASIC_AUTH
              - name: AINO_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: agent-msw
                    key: AINO_API_KEY
          restartPolicy: Never
